---
- name: Export Ansible Controller 1 & Import into Ansible Controller 2
  hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
  
    - name: Export all assets
      register: controller_inventory
      ansible.controller.export:
        inventory: ['all']
        controller_host: "{{controller_host1}}"
        controller_username: "{{controller_username1}}"
        controller_password: "{{controller_password1}}"
        validate_certs: False
        
    - name: Import Controller Projects
      ansible.controller.import:
        assets: "{{ controller_inventory.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
