---
- name: Export Controller 1 & Import into Controller 2
  hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
  
    - name: Export all assets
      register: controller_config
      ansible.controller.export:
        all: True
        controller_host: "{{controller_host1}}"
        controller_oauthtoken: "{{controller_token1}}"
        validate_certs: False
      

    - name: Import Controller Projects
      ansible.controller.import:
        assets: "{{ controller_config.assets }}"
        controller_host: "{{controller_host2}}"
        controller_oauthtoken: "{{controller_token2}}"
        validate_certs: False
